### ISSUE TITLE
Is this only working in India? 

### ISSUE THREAD

**Issue by GRACie-LoU-07** [iMro0t/bomb3r#3]
Do any of the SMS API's support USA?  Can you add variable to change default cc?

**Comment by iMro0t** [comment]
> Do any of the SMS API's support USA? Can you add variable to change default cc?

not all but few of them are works with different countries but some of them have cc parameter but still you'll not get sms so i ended up with default 91

**Comment by goldjunge91** [comment]
how can i use it in germany ?

**Comment by iMro0t** [comment]
> how can i use it in germany ?

i am currently working on it. you have to pass new argument and you can use in any country. i will commit in 2-3 days
