### ISSUE TITLE
access for russia numbers

### ISSUE THREAD

**Issue by towuk118** [iMro0t/bomb3r#4]
![image](https://user-images.githubusercontent.com/28830162/82835937-16ba9680-9ece-11ea-85b6-4abbfefabaa7.png)
### **add access to whrite RU numbers (for Russia)**

**Comment by iMro0t** [comment]
You have to use --country option and provide country code of russia. 
Eg. `python3 bomber.py 9999999999 --country 7`
read [here](https://github.com/iMro0t/bomb3r#options) for more details
